
sudo: required

language: python
python: "3.6"
node_js: "10"

services:
   - docker

before_install:
  - docker pull arangodb/arangodb:latest
  - docker pull waisbrot/wait:latest
  - docker run -e ARANGO_ROOT_PASSWORD='' -d -p 8529:8529 --name db arangodb/arangodb:latest
  - docker run --link db:db waisbrot/wait
  - npm i -g npm@latest


install:
  - pip install pipenv
  - pipenv install --dev --system --deploy

script:
  - pytest
  - cd yeti/web/frontend && npm install && npm run unit
  - npm ls && npm outdated
